title: "WPContractors"
description: >-
url: "https://www.wpcontractors.com"
email: service@esteemed.io

# Build settings
markdown: kramdown
plugins:
  - jekyll-get-json
  - jekyll-menus

jekyll_get_json:
  - data: profiles
    json: 'https://8mrb1284ud.execute-api.us-east-1.amazonaws.com/dev/profiles?channel=CUN3PEEAY'

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
sass:
  load_paths:
    - _sass
    - node_modules
exclude:
  - vendor
