title: "WPContractors"
description: >-
url: "https://www.wpcontractors.com"
email: service@esteemed.io

collections:
  skills:
    output: true
    permalink: /:collection/:name

# Build settings
markdown: kramdown
plugins:
  - jekyll-get-json
  - jekyll-datapage-generator
  - jekyll-menus

jekyll_get_json:
  - data: profiles
    json: 'https://8mrb1284ud.execute-api.us-east-1.amazonaws.com/dev/profiles?channel=CUN3PEEAY'
  - data: jobs
    json: 'https://8mrb1284ud.execute-api.us-east-1.amazonaws.com/dev/jobs'
  - data: config
    json: 'https://8mrb1284ud.execute-api.us-east-1.amazonaws.com/dev/config'

page_gen-dirs: true
page_gen:
  - data: "profiles"
    template: "contractor"
    name: "id"
    dir: "profile"
  - data: "config.titles"
    template: "contractors"
    name: "key"
    dir: "contractors"
  - data: "config.skills"
    template: "contractors"
    name: "key"
    dir: "skills"
  - data: "jobs"
    template: "job"
    name: "key"
    dir: "job"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
sass:
  load_paths:
    - _sass
    - node_modules
exclude:
  - gulpfile.js
  - package.json
  - package-lock.json
  - vendor
